# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: fix
        run: sudo chown -R $USER:$USER /home/ubuntu/actions-runner/project_folder/ruby_dump_api
      - uses: webfactory/ssh-agent@v0.5.0
        with:
            ssh-private-key: ${{ secrets.SSH_KEY }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: set env vars
        run: cp /home/ubuntu/ruby_dump_vars/.env .env
         
      - name: docker-compose down
        run: RAILS_ENV=production docker-compose down
      - name: docker-compose build
        run: RAILS_ENV=production docker-compose build
      - name: docker-compose up -d
        run: RAILS_ENV=production docker-compose up -d
      - name: run migrations
        run: RAILS_ENV=production docker-compose exec app bundle exec rake db:migrate

